__title__ = 'azurebloboperations'
__description__ = 'Code to upload, download and delete the file from Azure blob'
__url__ = 'https://github.com/prashantfb65/azurebloboperations'
__version__ = '0.1.0'
__author__ = 'Prashant Garg'
__author_email__ = 'PrashantRhel6@Gmail.com'
__license__ = 'MIT'
__copyright__ = 'Open source and freely distributed'